# ========================================================================================================================================
# CONFIGURAÇÕES DO SPRING BOOT
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
# ========================================================================================================================================

server:
  port: 8082  

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: ADMINISTRATIVO-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/administrativo
    username: root
    password: root # Bl@s100904
  jpa:
    hibernate:
      ddl-auto: none
