CREATE TABLE MUNICIPIO2 (
	CODIGO_IBGE INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CODIGO_UF INT NOT NULL,
	UF VARCHAR(2) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	LATITUDE FLOAT(8) NOT NULL,
	LONGITUDE FLOAT(8) NOT NULL,
	PRIMARY KEY(CODIGO_IBGE)
);

