# ========================================================================================================================================
# CONFIGURAÇÕES DO SPRING BOOT
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
# ========================================================================================================================================

server:
  port: 8083  

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: AGENDAMENTO-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/agendamento
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
